### ISSUE TITLE
Pic无法正确上传图片

### ISSUE THREAD

**Issue by alei643** [MYXXTS/Chevereto-Upload#2]
感谢开发V4版本插件，但我在使用过程中出现问题，之前使用兰空图床，可以使用PicGo正常上传。Chevereto使用公共key与个人key均无法正常上传，参数设置仅填写了API url与key

使用环境：
PicGo 2.3.1
Chevereto 4.04

![1673311422288](https://user-images.githubusercontent.com/38073408/211438835-a713d5f0-b278-4b6b-821f-6e8bd375b61a.png)

以下为PicGo的错误日志
`2023-01-10 08:51:27 [PicGo INFO] Before transform 
2023-01-10 08:51:27 [PicGo INFO] Transforming... Current transformer is [path] 
2023-01-10 08:51:27 [PicGo INFO] Before upload 
2023-01-10 08:51:27 [PicGo INFO] beforeUploadPlugins: renameFn running 
2023-01-10 08:51:27 [PicGo INFO] Uploading... Current uploader is [cheveretov4] 
2023-01-10 08:51:27 [PicGo WARN] failed 
2023-01-10 08:51:27 [PicGo ERROR] 
------Error Stack Begin------
TypeError: Cannot use 'in' operator to search for 'value' in null
    at mt (C:\Users\Administrator\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:47504)
    at C:\Users\Administrator\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:49862
    at Ut.request (C:\Users\Administrator\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:50075)
    at Object.handle (C:\Users\Administrator\AppData\Roaming\picgo\node_modules\picgo-plugin-cheveretov4\src\index.js:29:38)
    at $e.doUpload (C:\Users\Administrator\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:17221)
    at $e.start (C:\Users\Administrator\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:15980)
    at async Tt.upload (C:\Users\Administrator\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:71270)
    at async Object.upload (C:\Users\Administrator\AppData\Local\Programs\PicGo\resources\app.asar\background.js:2:653584)
    at async jn (C:\Users\Administrator\AppData\Local\Programs\PicGo\resources\app.asar\background.js:2:656251)
-------Error Stack End------- 
2023-01-10 08:51:27 [PicGo ERROR] 
------Error Stack Begin------
TypeError: Cannot use 'in' operator to search for 'value' in null
    at mt (C:\Users\Administrator\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:47504)
    at C:\Users\Administrator\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:49862
    at Ut.request (C:\Users\Administrator\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:50075)
    at Object.handle (C:\Users\Administrator\AppData\Roaming\picgo\node_modules\picgo-plugin-cheveretov4\src\index.js:29:38)
    at $e.doUpload (C:\Users\Administrator\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:17221)
    at $e.start (C:\Users\Administrator\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:15980)
    at async Tt.upload (C:\Users\Administrator\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:71270)
    at async Object.upload (C:\Users\Administrator\AppData\Local\Programs\PicGo\resources\app.asar\background.js:2:653584)
    at async jn (C:\Users\Administrator\AppData\Local\Programs\PicGo\resources\app.asar\background.js:2:656251)
-------Error Stack End------- 
`

**Comment by MYXXTS** [comment]
您好，感谢您使用本插件，初次安装给您带来不好的体验十分抱歉

为了更好的排查此问题以便于修复，请您进行以下操作：
1. 请问您使用的是 Public API key 也就是 Guest API 的上传 KEY 吗？
2. 请您在 picgo 设置 => 设置日志文件 点击设置 => 日记记录等级选择全部 => 打开日志文件，删除之前的日志并保存 => 重新上传以复现您的问题 => 按照方才的步骤打开日志文件，复制其中的内容给我。

感谢您的参与以便于完善此插件

**Comment by alei643** [comment]
1、使用Public API Key与User API key 我都已经测试过，均无法正确上传
2、我上贴提交的日志，就是清空日志后重新执行上传操作之后的日志。

我使用APIPost软件进行接口调试，可以正确上传，使用PicGo插件 Web Uploader 1.1.1插件自定义API参数，上传也没有问题

**Comment by MYXXTS** [comment]
已更新至1.1.2，请重试一下

**Comment by MYXXTS** [comment]
已更新至1.1.3，请更新重试
